name: Build and Test Linux
on: [push, pull_request]
jobs:
  build-linux:
    name: Python (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    env:
      PROJ_DIR: /usr
      PROJ_LIB: /usr/share/proj
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        #python-version: ["3.9"]
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ubuntu Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libproj-dev proj-bin libeccodes-dev
        sudo apt-get install libgeos-dev

    - name: Update Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install pygrib dependencies via pip
      run: |
        python -m pip install numpy
        python -m pip install cython
        python -m pip install pyproj
        python -m pip install pytest
        python -m pip install check-manifest
        python -m pip install twine
        python -m pip install wheel
        # below here only needed for mpl/cartopy based tests
        python -m pip install pytest-mpl
        python -m pip install pyshp
        python -m pip install six
        python -m pip install shapely --no-binary shapely
        python -m pip install matplotlib
        python -m pip install cartopy
        python -m pip install scipy
        python -m pip install pyspharm

    - name: Install pygrib
      run: |
        python setup.py install
    - name: Test
      run: |
        cd test
        export MPLBACKEND=agg
        pytest test*py --mpl --mpl-baseline-path=baseline_images
        # if no mpl/cartopy run this
        #pytest test.py test_latlons.py

    - name: Tarball
      run: |
        python setup.py --version ; 
        pip wheel . -w dist --no-deps ;
        check-manifest --verbose ;
        twine check dist/* ;
